export default [
  { src: `${process.env.PUBLIC_URL}/img/img/Resturant 1.jpeg`, type: 'restaurants', alt: 'restaurants' },
  { src: `${process.env.PUBLIC_URL}/img/img/Resturant 2.jpeg`, type: 'restaurants', alt: 'restaurants' },
  { src: `${process.env.PUBLIC_URL}/img/img/Resturant 3.jpeg`, type: 'restaurants', alt: 'restaurants' },
  { src: `${process.env.PUBLIC_URL}/img/img/Resturant 4.jpeg`, type: 'restaurants', alt: 'restaurants' },
  { src: `${process.env.PUBLIC_URL}/img/img/Resturant 5.jpeg`, type: 'restaurants', alt: 'restaurants' },
  { src: `${process.env.PUBLIC_URL}/img/img/Resturant 6.jpeg`, type: 'restaurants', alt: 'restaurants' },
  { src: `${process.env.PUBLIC_URL}/img/img/beef.jpg`, type: 'products', alt: 'products' },
  { src: `${process.env.PUBLIC_URL}/img/img/cw.jpg`, type: 'products', alt: 'products' },
  { src: `${process.env.PUBLIC_URL}/img/img/vw.jpg`, type: 'products', alt: 'products' },
  { src: `${process.env.PUBLIC_URL}/img/img/bb.jpg`, type: 'products', alt: 'products' },
  { src: `${process.env.PUBLIC_URL}/img/img/cf.jpg`, type: 'products', alt: 'products' },
  { src: `${process.env.PUBLIC_URL}/img/img/ccs.jpg`, type: 'products', alt: 'products' },
  { src: `${process.env.PUBLIC_URL}/img/img/dfcr.jpg`, type: 'products', alt: 'products' },
  { src: `${process.env.PUBLIC_URL}/img/img/mm.jpg`, type: 'products', alt: 'products' },
  { src: `${process.env.PUBLIC_URL}/img/img/ls.jpg`, type: 'products', alt: 'products' },
  { src: `${process.env.PUBLIC_URL}/img/img/cb.jpg`, type: 'products', alt: 'products' },
  { src: `${process.env.PUBLIC_URL}/img/img/meat.jpg`, type: 'products', alt: 'products' },
  { src: `${process.env.PUBLIC_URL}/img/img/swwet.jpg`, type: 'products', alt: 'products' },
  { src: `${process.env.PUBLIC_URL}/img/img/s&t.jpg`, type: 'products', alt: 'products' },
  { src: `${process.env.PUBLIC_URL}/img/img/wedges.jpg`, type: 'products', alt: 'products' },
  { src: `${process.env.PUBLIC_URL}/img/img/fries.jpg`, type: 'products', alt: 'products' },
  { src: `${process.env.PUBLIC_URL}/img/img/salad.jpg`, type: 'products', alt: 'products' },
  { src: `${process.env.PUBLIC_URL}/img/img/vegies.jpg`, type: 'products', alt: 'products' },
  { src: `${process.env.PUBLIC_URL}/img/img/rice.jpg`, type: 'products', alt: 'products' },
  { src: `${process.env.PUBLIC_URL}/img/img/pepper.jpg`, type: 'products', alt: 'products' },
  { src: `${process.env.PUBLIC_URL}/img/img/mushroom.jpg`, type: 'products', alt: 'products' },
  { src: `${process.env.PUBLIC_URL}/img/img/cheese.jpg`, type: 'products', alt: 'products' },
  { src: `${process.env.PUBLIC_URL}/img/img/gmc.jpg`, type: 'products', alt: 'products' },
  { src: `${process.env.PUBLIC_URL}/img/img/quewsadilla.jpg`, type: 'products', alt: 'products' },
  { src: `${process.env.PUBLIC_URL}/img/img/pizza.jpg`, type: 'products', alt: 'products' },  
  { src: `${process.env.PUBLIC_URL}/img/img/slice.jpg`, type: 'products', alt: 'products' },
  { src: `${process.env.PUBLIC_URL}/img/img/club.jpg`, type: 'products', alt: 'products' },
  { src: `${process.env.PUBLIC_URL}/img/img/vclub.jpg`, type: 'products', alt: 'products' },
  { src: `${process.env.PUBLIC_URL}/img/img/beefstir.jpg`, type: 'products', alt: 'products' },
  { src: `${process.env.PUBLIC_URL}/img/img/vegstir.jpg`, type: 'products', alt: 'products' },
  { src: `${process.env.PUBLIC_URL}/img/img/meetbasket.jpg`, type: 'products', alt: 'products' },
  { src: `${process.env.PUBLIC_URL}/img/img/SeafoodBasket.jpeg`, type: 'products', alt: 'products' },
  { src: `${process.env.PUBLIC_URL}/img/img/BeefBurger.jpeg`, type: 'products', alt: 'products' },  
  { src: `${process.env.PUBLIC_URL}/img/img/ChickenBurger.jpeg`, type: 'products', alt: 'products' },
  { src: `${process.env.PUBLIC_URL}/img/img/Kapana.jpeg`, type: 'products', alt: 'products' },
  { src: `${process.env.PUBLIC_URL}/img/img/MixedPlatter.jpeg`, type: 'products', alt: 'products' },
  { src: `${process.env.PUBLIC_URL}/img/img/FruitPlatter.jpeg`, type: 'products', alt: 'products' },
  { src: `${process.env.PUBLIC_URL}/img/img/HamAndCheddar.jpeg`, type: 'products', alt: 'products' },
  { src: `${process.env.PUBLIC_URL}/img/img/GrilledChickenAndMayonnaise.jpeg`, type: 'products', alt: 'products' },
  { src: `${process.env.PUBLIC_URL}/img/img/RoastedVegetablesAndBasilPesto.jpeg`, type: 'products', alt: 'products' },
  { src: `${process.env.PUBLIC_URL}/img/img/ChickenWings.jpeg`, type: 'products', alt: 'products' },
  { src: `${process.env.PUBLIC_URL}/img/img/ChickenSchnitzel.jpeg`, type: 'products', alt: 'products' },
  { src: `${process.env.PUBLIC_URL}/img/img/BeefSchnitzel.jpeg`, type: 'products', alt: 'products' },
  { src: `${process.env.PUBLIC_URL}/img/img/BeefOrChickenBurgerAndChips.jpeg`, type: 'products', alt: 'products' },
  { src: `${process.env.PUBLIC_URL}/img/img/ClassicBatteredFishAndChips.jpeg`, type: 'products', alt: 'products' },
  { src: `${process.env.PUBLIC_URL}/img/img/Sweet&SourStir-FryWithVegetables.jpeg`, type: 'products', alt: 'products' },
  { src: `${process.env.PUBLIC_URL}/img/img/ThePelicanMeatyBasket.jpeg`, type: 'products', alt: 'products' },
  { src: `${process.env.PUBLIC_URL}/img/img/ThePelicanSeafoodBasket.jpeg`, type: 'products', alt: 'products' },
  { src: `${process.env.PUBLIC_URL}/img/img/SEAFOODBOILFORONE.jpeg`, type: 'products', alt: 'products' },
  { src: `${process.env.PUBLIC_URL}/img/img/PremiumCakeSlice.jpeg`, type: 'products', alt: 'products' },
  { src: `${process.env.PUBLIC_URL}/img/img/BranMuffin.jpeg`, type: 'products', alt: 'products' },
  { src: `${process.env.PUBLIC_URL}/img/img/Scone.jpeg`, type: 'products', alt: 'products' },
  { src: `${process.env.PUBLIC_URL}/img/img/Margherita.jpeg`, type: 'products', alt: 'products' },
  { src: `${process.env.PUBLIC_URL}/img/img/MeatyBoy.jpeg`, type: 'products', alt: 'products' },
  { src: `${process.env.PUBLIC_URL}/img/img/Vegetarian.jpeg`, type: 'products', alt: 'products' },
  { src: `${process.env.PUBLIC_URL}/img/img/Cosmopolitan.jpeg`, type: 'products', alt: 'products' },
  { src: `${process.env.PUBLIC_URL}/img/img/Mexican.jpeg`, type: 'products', alt: 'products' },
  { src: `${process.env.PUBLIC_URL}/img/img/4Cheeses.jpeg`, type: 'products', alt: 'products' },
  { src: `${process.env.PUBLIC_URL}/img/img/GrilledNamibianHake.jpeg`, type: 'products', alt: 'products' },
  { src: `${process.env.PUBLIC_URL}/img/img/TraditionalFreeRangeChicken.jpeg`, type: 'products', alt: 'products' },
  { src: `${process.env.PUBLIC_URL}/img/img/ChickenFillet.jpeg`, type: 'products', alt: 'products' },
  { src: `${process.env.PUBLIC_URL}/img/img/HomeMadeVegetarian.jpeg`, type: 'products', alt: 'products' },
  { src: `${process.env.PUBLIC_URL}/img/img/Beef200g.jpeg`, type: 'products', alt: 'products' },
  { src: `${process.env.PUBLIC_URL}/img/img/PizzaSliceCombo.jpeg`, type: 'products', alt: 'products' },
  { src: `${process.env.PUBLIC_URL}/img/img/chickenlivers.jpeg`, type: 'products', alt: 'products' },
  { src: `${process.env.PUBLIC_URL}/img/img/ButterChickenCarry.jpeg`, type: 'products', alt: 'products' },
  { src: `${process.env.PUBLIC_URL}/img/img/oxtail.jpeg`, type: 'products', alt: 'products' },
  { src: `${process.env.PUBLIC_URL}/img/img/BeefStew.jpeg`, type: 'products', alt: 'products' },
  { src: `${process.env.PUBLIC_URL}/img/img/bream.jpeg`, type: 'products', alt: 'products' },
  { src: `${process.env.PUBLIC_URL}/img/img/tbonesteak.jpeg`, type: 'products', alt: 'products' },
  { src: `${process.env.PUBLIC_URL}/img/img/ChickenFilletBurger.jpeg`, type: 'products', alt: 'products' },
  { src: `${process.env.PUBLIC_URL}/img/img/BeefBurger2.jpeg`, type: 'products', alt: 'products' },
];
